### ISSUE TITLE
Form compiling page and error in side bar link 

### ISSUE THREAD

**Issue by marco55555** [puria/ksweb#117] opened 2019-04-03 17:40 UTC
![Schermata da 2019-02-07 17-19-38](https://user-images.githubusercontent.com/28400805/55500326-64c86700-5648-11e9-8096-df9c3d4ce50d.png)
![Schermata da 2019-02-07 17-19-43](https://user-images.githubusercontent.com/28400805/55500327-64c86700-5648-11e9-9cf4-4059c3a79ec9.png)

**Comment by puria** [comment] 2020-06-05 10:31
duplicate of #110

**Closed by puria** 2020-06-05 10:31 UTC
Labels: duplicate
