### ISSUE TITLE
Create new Workspace with Safari

### ISSUE THREAD

**Issue by marco55555** [puria/ksweb#36] opened 2018-03-27 15:27 UTC
MacOS 10.12.6 (16G1212) and Safari 11.0.3 (12604.5.6.1.1) do not allow to create new Workspace

**Comment by puria** [comment] 2018-03-28 11:27
I was not able to reproduce it. Which user? Gives an error, in the console?

**Comment by puria** [comment] 2018-03-29 10:46
Tried and in any way I'm able to create workspaces. I guess could be related to #37 that is already closed. So will close this for now.

**Comment by puria** [comment] 2018-03-29 10:47
#37

**Closed by puria** 2018-03-29 10:46 UTC
Labels: bug
